allow_username_mismatch = false;
allow_hdrfrom_mismatch = false;
sign_authenticated = true;
sign_local = false;
use_domain = "header";
use_esld = false;
selector = "nsoft2026";
path = "/data/dkim/$domain/$selector.key";
