protocols = imap lmtp sieve
listen = *
mail_plugins = quota
mail_location = maildir:/var/vmail/%d/%n/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
ssl = required
ssl_min_protocol = TLSv1.2
ssl_cert = </data/tls/fullchain.pem
ssl_key = </data/tls/privkey.pem
disable_plaintext_auth = yes
auth_mechanisms = plain login
auth_username_format = %Lu
log_path = /dev/stderr
info_log_path = /dev/stdout
passdb {
  driver = sql
  args = /etc/dovecot/sql.conf
}
userdb {
  driver = sql
  args = /etc/dovecot/sql.conf
}
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}
service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}
service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}
protocol imap {
  mail_plugins = quota imap_quota
}
protocol lmtp {
  mail_plugins = quota sieve
  postmaster_address = postmaster@__MAIL_HOSTNAME__
}
plugin {
  quota = count:User quota
  quota_vsizes = yes
  quota_grace = 10%
  sieve_before = /opt/nsoft/spam.sieve
  sieve = file:~/sieve;active=~/.dovecot.sieve
}
service auth-worker {
  user = dovecot
}
service auth {
  vsz_limit = 2G
}
