[supervisord]
user=root
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid
[program:postfix]
command=/usr/sbin/postfix start-fg
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:maintenance]
command=python3 /opt/nsoft/maintenance.py
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
